# Generated by Django 3.2.8 on 2021-10-05 12:15

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='entered phone number is invalid.', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'merchant',
                'verbose_name_plural': 'merchants',
                'ordering': ['last_name'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='payment amount')),
                ('link', models.CharField(max_length=36, unique=True, verbose_name='link')),
                ('max_payments_count', models.PositiveSmallIntegerField(default=0, verbose_name='maximum payments count')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation cate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_forms', to='merchants.merchant', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'payment form',
                'verbose_name_plural': 'payment forms',
                'ordering': ['-creation_date'],
            },
        ),
    ]
