# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('link', models.CharField(max_length=36, verbose_name='link')),
                ('payable_times', models.PositiveSmallIntegerField(default=0, verbose_name='payable times')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'payment form',
                'verbose_name_plural': 'payment forms',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['last_name'], 'verbose_name': 'merchant', 'verbose_name_plural': 'merchants'},
        ),
        migrations.AddField(
            model_name='paymentform',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_forms', to='merchants.Merchant', verbose_name='creator'),
        ),
    ]
