# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_auto_20190508_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
