# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentform',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation cate'),
        ),
    ]
