# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_auto_20190508_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
