# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 12:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_auto_20190512_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='entered phone number is invalid.', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
