# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0007_auto_20190512_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentform',
            old_name='price',
            new_name='payment_amount',
        ),
    ]
