# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0008_auto_20190512_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentform',
            name='payable_times',
        ),
        migrations.AddField(
            model_name='paymentform',
            name='max_payments_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='maximum payments count'),
        ),
    ]
