# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0010_auto_20190514_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentform',
            name='link',
            field=models.CharField(max_length=36, unique=True, verbose_name='link'),
        ),
    ]
