# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0011_auto_20190515_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentform',
            old_name='creator',
            new_name='owner',
        ),
    ]
