# Generated by Django 3.2.8 on 2021-10-05 12:15

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='entered phone number is invalid.', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'payer',
                'verbose_name_plural': 'payers',
                'ordering': ['last_name'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(default='', max_length=36, verbose_name='authority')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='payment amount')),
                ('status_code', models.IntegerField(null=True, verbose_name='status code')),
                ('status', models.SmallIntegerField(choices=[(0, 'pending'), (1, 'successful'), (2, 'failed')], default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='transactions.payer', verbose_name='payer')),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='merchants.paymentform', verbose_name='payment form')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-creation_date'],
            },
        ),
    ]
