# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 13:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-creation_date'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='started_date',
            new_name='creation_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ended_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_code',
            field=models.IntegerField(null=True, verbose_name='status code'),
        ),
        migrations.AlterField(
            model_name='payer',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='entered phone number is invalid.', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.PositiveIntegerField(verbose_name='payment amount'),
        ),
    ]
