# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20190512_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payer',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
