# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20190512_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price',
            new_name='payment_amount',
        ),
    ]
