# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20190512_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (1, 'successful'), (2, 'failed')], default=0),
        ),
    ]
