# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 21:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='entered phone number is invalid.', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
