# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20190514_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payer',
        ),
    ]
