# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_transaction_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payer',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='transactions.Payer', verbose_name='payer'),
            preserve_default=False,
        ),
    ]
