# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='authority',
            field=models.CharField(default=django.utils.timezone.now, max_length=36, verbose_name='authority'),
            preserve_default=False,
        ),
    ]
