# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='authority',
            field=models.CharField(default='', max_length=36, verbose_name='authority'),
        ),
    ]
